### ISSUE TITLE
SandBox API not working - error500 

### ISSUE THREAD

**Issue by Juanjoarlandis** [quantnetwork/blockchain-developer-exercises-foundations#12]
Hi, today I was doing some stuff with the sandbox api and realised that the api wasnt working anymore. 
I only get the 500error with a timeout=5000ms.

Maybe there is a maintennance ongoing, but its quite strange.

@andynelson @jvaralves @lukerQuant @RafaelAPB

**Comment by lukerQuant** [comment]
Hi @Juanjoarlandis can you provide more details regarding what specific API you were using?

**Comment by Juanjoarlandis** [comment]
[2023-02-21T00:09:41.591] [ERROR] contract_invoke -  Error: timeout of 5000ms exceeded
    at createError (/Users/juanjoarlandis/OVERLEDGER/OVL_funciones/blockchain-developer-exercises-foundations-main/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/Users/juanjoarlandis/OVERLEDGER/OVL_funciones/blockchain-developer-exercises-foundations-main/node_modules/axios/lib/adapters/http.js:303:16)
    at RedirectableRequest.emit (node:events:394:28)
    at RedirectableRequest.emit (node:domain:470:12)
    at Timeout.<anonymous> (/Users/juanjoarlandis/OVERLEDGER/OVL_funciones/blockchain-developer-exercises-foundations-main/node_modules/follow-redirects/index.js:164:12)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  config: {
    url: '/preparation/transaction',
    method: 'post',
    data: '{"type":"PAYMENT","location":{"technology":"Ethereum","network":"Avalanche Fuji Testnet"},"urgency":"normal","requestDetails":{"overledgerSigningType":"overledger-javascript-library","message":"This TX was made by Juanjo through the Overledger JavaScript SDK, for my twitter lads :) ","origin":[{"originId":"0x2495FfBA1e398144297aab5d38024A153A4733e3"}],"destination":[{"destinationId":"0x7342fa73E9e3938a4ceEcDB7C13Fd9296D313D55","payment":{"amount":"0.0001","unit":"AVAX"}}]}}',
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
      Authorization: 'Bearer  ',
      'User-Agent': 'axios/0.21.4',
      'Content-Length': 478
    },
    baseURL: 'https://api.sandbox.overledger.io/v2',
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 5000,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    }
  },
  code: 'ECONNABORTED',
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: destroyOnTimeout]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/v2/preparation/transaction',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'api.sandbox.overledger.io',
      port: null,
      nativeProtocols: [Object],
      pathname: '/v2/preparation/transaction'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 478,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /v2/preparation/transaction HTTP/1.1\r\n' +
        'Accept: application/json\r\n' +
        'Content-Type: application/json\r\n' +
        'Authorization: Bearer ' +
        'User-Agent: axios/0.21.4\r\n' +
        'Content-Length: 478\r\n' +
        'Host: api.sandbox.overledger.io\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/v2/preparation/transaction',
      _ended: false,
      res: null,
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.sandbox.overledger.io',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kError)]: undefined
    },
    _currentUrl: 'https://api.sandbox.overledger.io/v2/preparation/transaction',
    _timeout: null,
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]

**Comment by Juanjoarlandis** [comment]
I got it again today, some hours ago it was working, now gives me this error again.

**Comment by lukerQuant** [comment]
Hi @Juanjoarlandis . Ah ok this is a client side timeout error from our SDK. 

We are in the process of adding more node resources onto our public Overledger instance, but for now it might be beneficial for you to increase the timeout parameter passed to the OverledgerSDK Object (described here: https://github.com/quantnetwork/overledger-sdk-javascript-v2/blob/cfa652e68a93c8b10eab540fbf69f282f3c0aa21/packages/overledger-types/README.md#provideroptions).

I will update the examples of this repo soon to include this timeout parameter.

**Comment by Juanjoarlandis** [comment]
Thanks for your response!

I have two more questions if it would be possible.

1- The first one is that in my case the polygon mumbai testnet process of posting the transaction request gives a -3200 error that has to do with the gas. I manually increased, but it looks like if the SDK is not being able to obtain the correct amount of gas needed. This is the response I obtain:
<img width="965" alt="Captura de Pantalla 2023-02-21 a las 9 54 11" src="https://user-images.githubusercontent.com/96684746/220295886-2480aa3c-d35f-48dd-aa70-d52d85d33d4f.png">


2 - The second question is if its possible to make bulk transfers through the API call. Let's say I prepare 10 tx, it would be possible to post them at the same time actioning any type of 2 phase commit process, or it needs to be done atomically.

Thanks for your time, amazing work!
@lukerQuant

**Comment by lukerQuant** [comment]
1. Polygon is not supposed to be covered by this course. Well done for editing the examples to use it though. Can you instead raise that issue through our zendesk system by emailing: support@quant.zendesk.com

2. This is not possible through a normal API but exists in one of our QRC tiers as a smart contract function (I'm not sure this tier is publicly released yet).

**Comment by Juanjoarlandis** [comment]
Sure, thanks for your time!
