### ISSUE TITLE
Week 1 Introduction issue

### ISSUE THREAD

**Issue by jdmurphy96** [quantnetwork/blockchain-developer-exercises-foundations#13]
I am trying to run the following command "npm-run secure-env .env -s MY_PASSWORD" after all the previous steps however, I keep receiving a "not found: secure-env" message. Could anyone advise on how to resolve this please?

**Comment by lukerQuant** [comment]
Hi @jdmurphy96 , this error message means that you have not installed the 'secure-env' program on your laptop.

To do so, try:
```
npm install secure-env
```
or alternatively:
```
npm install -g secure-env
```

**Comment by jdmurphy96** [comment]
<img width="1667" alt="Screenshot 2023-02-21 at 19 04 45" src="https://user-images.githubusercontent.com/113718237/220436573-8066607d-e09b-455a-af52-77616ec6a61b.png">

Hi Luke @lukerQuant, 

Thanks for your help.

I'm still having the same issue, please see attached photograph. I have tried both methods above. 

Kind Regards,

Jamie

**Comment by lukerQuant** [comment]
Hi @jdmurphy96 ,

If you look again at https://github.com/quantnetwork/blockchain-developer-exercises-foundations/blob/main/Exercise1.md#securing-your-overledger-connection-details, there are alternative command line options (3 in total) if the first one that you tried does not work.

**Comment by lukerQuant** [comment]
Hi @jdmurphy96 I haven't heard back from you for a while, so I assume you sorted this out after further reading

**Comment by jdmurphy96** [comment]
Hi Luke,

Thanks for getting in contact.

I still had issues with the week 1 tasks, nothing I tried seemed to work so I gave up. I may need improve on my coding knowledge before returning to this course, as of yet I only understand the very basics of java from Sololearn. Could I ask if there is anything you would recommend I should learn first before attempting this course again?

Kind Regards,

Jamie
________________________________

**Comment by lukerQuant** [comment]
Hi Jamie, 

If you are still having an issue, please send the info to support@quant.zendesk.com and the team can provide you more support.

Regards,

Luke
