### ISSUE TITLE
Error in NewDeviceMetadata

### ISSUE THREAD

**Issue by Juanjoarlandis** [quantnetwork/blockchain-developer-exercises-foundations#14]
Hello today I tried to run the configure-sdk.js and In the loging and verification part returns the following error. @lukerQuant 

![Screenshot from 2023-03-16 14-53-40](https://user-images.githubusercontent.com/96684746/225639378-e491209c-fa28-44d3-b2d5-f4a9410a0f75.png)

**Comment by Juanjoarlandis** [comment]
I came back to the developerscourse exercises because in my testing enviroment I was getting the same error.

**Comment by lukerQuant** [comment]
Hi @Juanjoarlandis , please raise this with support@quant.zendesk.com and include your clientId. You will receive a reply through that system.
